vich_uploader:
    db_driver: orm
    mappings:
        document:
            inject_on_load: true
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%/document"
            upload_destination: document_fs
            delete_on_update: false
            delete_on_remove: false
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
